# Generated by Django 4.2.4 on 2024-05-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_customer_organization_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRegion',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tax.customer')),
                ('region', models.CharField(choices=[('AR', 'Arusha'), ('DS', 'Dar es Salaam\t'), ('Do', 'Dodoma'), ('GE', 'Geita'), ('IR', 'Iringa'), ('KA', 'Kagera'), ('KT', 'Katavi'), ('KG', 'Kigoma'), ('KI', 'Kilimanjaro'), ('LI', 'Lindi'), ('MA', 'Manyara'), ('MR', 'Mara'), ('MB', 'Mbeya'), ('MM', 'Mjini Magharibi'), ('MO', 'Morogoro'), ('MT', 'Mtwara'), ('MW', 'Mwanza'), ('NJ', 'Njombe'), ('PN', 'Pemba North Region'), ('PS', 'Pemba South Region'), ('PW', 'Pwani'), ('RU', 'Rukwa'), ('RV', 'Ruvuma'), ('SH', 'Shinyanga'), ('SI', 'Simiyu'), ('SG', 'Singida'), ('SW', 'Songwe'), ('TA', 'Tabora'), ('TN', 'Tanga'), ('UN', 'Unguja North Region'), ('US', 'Unguja South Region')], max_length=2)),
                ('district', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization_type',
            field=models.CharField(choices=[('O', 'Others'), ('TR', 'Non Government'), ('GO', 'Government'), ('LC', 'Limited Company'), ('PJ', 'Partner / Joint Venture')], max_length=2),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('message_alert', models.CharField(choices=[('NU', 'Not Urgent'), ('MO', 'Moderate'), ('UR', 'Urgent')], default='NU', max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tax.customer')),
            ],
        ),
    ]
