# Generated by Django 5.0.6 on 2024-05-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_taxregion_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='info@email.com', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization_type',
            field=models.CharField(choices=[('OT', 'Others'), ('TR', 'Non Government'), ('GO', 'Government'), ('LC', 'Limited Company'), ('PJ', 'Partner / Joint Venture')], max_length=2),
        ),
    ]
