# Generated by Django 5.0.6 on 2024-05-22 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_customer_email_alter_customer_organization_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taxregion',
            options={'ordering': ['region', 'district']},
        ),
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.customer'),
        ),
        migrations.AlterField(
            model_name='taxregion',
            name='region',
            field=models.CharField(choices=[('AR', 'Arusha'), ('DS', 'Dar es Salaam\t'), ('DO', 'Dodoma'), ('GE', 'Geita'), ('IR', 'Iringa'), ('KA', 'Kagera'), ('KT', 'Katavi'), ('KG', 'Kigoma'), ('KI', 'Kilimanjaro'), ('LI', 'Lindi'), ('MA', 'Manyara'), ('MR', 'Mara'), ('MB', 'Mbeya'), ('MM', 'Mjini Magharibi'), ('MO', 'Morogoro'), ('MT', 'Mtwara'), ('MW', 'Mwanza'), ('NJ', 'Njombe'), ('PN', 'Pemba North Region'), ('PS', 'Pemba South Region'), ('PW', 'Pwani'), ('RU', 'Rukwa'), ('RV', 'Ruvuma'), ('SH', 'Shinyanga'), ('SI', 'Simiyu'), ('SG', 'Singida'), ('SW', 'Songwe'), ('TA', 'Tabora'), ('TN', 'Tanga'), ('UN', 'Unguja North Region'), ('US', 'Unguja South Region')], max_length=2),
        ),
    ]
