# Generated by Django 5.0.6 on 2024-06-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_alter_customer_options_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'permissions': [('cancel_message', 'Can cancel message')]},
        ),
    ]
